---

- name: update Homebrew
  homebrew:
    update_homebrew: yes

- name: upgrade all brew packages
  homebrew:
    upgrade_all: yes
  tags: [ 'never', 'upgrade' ]

- name: install Golang
  homebrew:
    name: go
    state: present

- name: application install
  homebrew_cask:
    name:
      - dash
      - docker
      - java
      - logitech-options
      - slack
      - spotify
      - visual-studio-code
      - zoomus
    state: present
- homebrew_cask:
    name:
      - choosy
      - firefox
      - google-backup-and-sync
      - google-chrome
      - karabiner-elements
      - thinkorswim
    state: absent