---

- name: update Homebrew
  homebrew:
    update_homebrew: yes

- name: upgrade all brew packages
  homebrew:
    upgrade_all: yes
  tags: [ 'never', 'upgrade' ]

- name: install Golang
  homebrew:
    name: go
    state: present
    
- name: install Google Chrome
  homebrew_cask:
    name: google-chrome
    state: present

- name: install Karabiner-Elements
  homebrew_cask:
    name: karabiner-elements
    state: present
