---

- git_config:
    name: core.editor
    scope: global
    value: vim

- git_config:
    name: user.name
    scope: global
    value: Anthony Sandoval

- git_config:
    name: user.email
    scope: global
    value: git@sdval.com
