---

- name: install tmux Darwin
  block:
    - homebrew:
        name: tmux
  when: ansible_facts['os_family'] == "Darwin"

- name: install tmux Debian
  block:
    - apt:
        name: tmux
        update_cache: yes
  become: true
  when: ansible_facts['os_family'] == "Debian"
