---

- name: install zsh deb package
  apt:
    name: zsh
    update_cache: yes
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: install zsh brew package
  homebrew:
    name: zsh
    state: present
  when: ansible_facts['os_family'] == "Darwin"

- name: change user shell to zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ '/usr/local/bin/zsh' if ansible_facts.os_family == 'Darwin' else '/usr/bin/zsh' }}"
  become: yes

- name: download oh-my-zsh install script
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/install-oh-my-zsh.sh
    mode: 0755

- name: execute oh-my-zsh install script
  shell: /tmp/install-oh-my-zsh.sh

- name: copy .zshrc file
  copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: 0644
